app:
  telegram-token: 6808272281:AAG4adIqTJ-PHv-ua3n3q6pvdqOHqptnYw8

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
