FROM openjdk:21-jdk-slim

COPY ./target/bot.jar /bot/bot.jar

WORKDIR /bot

EXPOSE 8090
EXPOSE 8091

ARG BOT_TOKEN_LIMIT="20"
ENV BOT_TOKEN_LIMIT=${BOT_TOKEN_LIMIT}

ARG BOT_REFILL_COUNT="1"
ENV BOT_REFILL_COUNT=${BOT_REFILL_COUNT}

ARG BOT_REFILL_DURATION="2s"
ENV BOT_REFILL_DURATION=${BOT_REFILL_DURATION}

ARG SCRAPPER_BASEURL_HOST="http://localhost"
ENV SCRAPPER_BASEURL_HOST=${SCRAPPER_BASEURL_HOST}

ENTRYPOINT ["java","-jar","/bot/bot.jar"]
